-- v12 M5 (G5): set-based fanout ranking over rows (semantic_find pattern).
--
-- One Choice question ranks up to 255 line ids at once (probabilities form
-- the ranking); a Noul existence question covers absence, because Choice
-- probabilities always sum to 1 and cannot express "nothing matches" on
-- their own. Documents larger than 255 lines go in two passes: a window
-- Choice first, then a line Choice inside the winning window.
--
-- The questions are generated by SQL from the table — DuckDB can feed the
-- same tables via postgres_scanner for analytics-scale fanout; nothing in
-- this stage is PG-specific beyond the queries.

CREATE TABLE fanout_docs (
    doc_id  text NOT NULL,
    line_no int NOT NULL CHECK (line_no >= 0),
    line    text NOT NULL,
    PRIMARY KEY (doc_id, line_no)
);

-- Pass 1 (only for docs > 255 lines): pick the window containing the answer.
-- Window state carries the full window text so the model has the material.
CREATE FUNCTION v12_fanout_open_windows(p_doc_id text, p_query text,
                                        p_window int DEFAULT 200)
RETURNS uuid
LANGUAGE plpgsql AS $$
DECLARE
    v_session uuid;
    v_batch uuid;
    v_max int;
    v_map jsonb := '{}';
    r record;
BEGIN
    IF p_window < 1 OR p_window > 255 THEN
        RAISE EXCEPTION 'v12: window size must be in [1, 255]';
    END IF;
    SELECT max(line_no) INTO v_max FROM fanout_docs WHERE doc_id = p_doc_id;
    IF v_max IS NULL THEN
        RAISE EXCEPTION 'v12: unknown doc %', p_doc_id;
    END IF;

    -- scratch session per doc batch (fanout is not conversational)
    INSERT INTO sessions (workspace_id) VALUES ('fanout')
    RETURNING session_id INTO v_session;

    FOR r IN
        SELECT (n * p_window) AS w_from,
               least((n * p_window) + p_window - 1, v_max) AS w_to
          FROM generate_series(0, v_max / p_window) n
    LOOP
        v_map := v_map || jsonb_build_object(
            'W' || (r.w_from / p_window),
            jsonb_build_object(
                'from', r.w_from, 'to', r.w_to,
                'text', (SELECT string_agg(line, E'\n' ORDER BY line_no)
                           FROM fanout_docs
                          WHERE doc_id = p_doc_id
                            AND line_no BETWEEN r.w_from AND r.w_to)));
    END LOOP;

    v_batch := v12_open_batch(v_session, 'fanout', jsonb_build_object(
        'doc_id', p_doc_id, 'query', p_query, 'windows', v_map));
    PERFORM v12_add_question(v_batch, 'window', 'choice',
        'Which window in `state.windows` contains the line that answers '
        '`state.query`? Choose the window id (W0, W1, ...).',
        (SELECT jsonb_object_agg(key, NULL)
           FROM jsonb_object_keys(v_map) key));
    RETURN v_batch;
END;
$$;

-- Pass 2: rank every line of a range (<= 255) with one Choice + existence
-- Noul. Also the single pass for docs that fit one window.
CREATE FUNCTION v12_fanout_open_lines(p_doc_id text, p_query text,
                                      p_from int, p_to int)
RETURNS uuid
LANGUAGE plpgsql AS $$
DECLARE
    v_session uuid;
    v_batch uuid;
    v_lines jsonb;
    v_count int;
BEGIN
    SELECT count(*) INTO v_count FROM fanout_docs
     WHERE doc_id = p_doc_id AND line_no BETWEEN p_from AND p_to;
    IF v_count = 0 THEN
        RAISE EXCEPTION 'v12: empty range %..% for doc %', p_from, p_to, p_doc_id;
    END IF;
    IF v_count > 255 THEN
        RAISE EXCEPTION 'v12: % lines exceeds the 255-option Choice limit; '
                        'narrow the window first', v_count;
    END IF;

    INSERT INTO sessions (workspace_id) VALUES ('fanout')
    RETURNING session_id INTO v_session;

    SELECT jsonb_object_agg('L' || lpad(line_no::text, 4, '0'), line)
      INTO v_lines
      FROM fanout_docs
     WHERE doc_id = p_doc_id AND line_no BETWEEN p_from AND p_to;

    v_batch := v12_open_batch(v_session, 'fanout', jsonb_build_object(
        'doc_id', p_doc_id, 'query', p_query, 'lines', v_lines));
    PERFORM v12_add_question(v_batch, 'where', 'choice',
        'Which line in `state.lines` contains the answer to `state.query`? '
        'Choose the line id.',
        (SELECT jsonb_object_agg(key, NULL) FROM jsonb_object_keys(v_lines) key));
    PERFORM v12_add_question(v_batch, 'exists', 'noul',
        'Does any line in `state.lines` address or answer `state.query`?');
    RETURN v_batch;
END;
$$;

-- Narrow an answered window batch into a line batch over the winning window.
-- Returns NULL when the batch is not a window batch.
CREATE FUNCTION v12_fanout_narrow(p_batch uuid) RETURNS uuid
LANGUAGE plpgsql AS $$
DECLARE
    v_state jsonb;
    v_choice text;
    v_win jsonb;
BEGIN
    SELECT state INTO v_state FROM jev_batches WHERE batch_id = p_batch;
    IF v_state IS NULL OR v_state -> 'windows' IS NULL THEN
        RETURN NULL;
    END IF;
    SELECT answer ->> 'choice' INTO v_choice
      FROM jev_decisions
     WHERE batch_id = p_batch AND question_id = 'window';
    IF v_choice IS NULL THEN
        RAISE EXCEPTION 'v12: batch % has no window decision yet', p_batch;
    END IF;
    v_win := v_state -> 'windows' -> v_choice;
    IF v_win IS NULL THEN
        RAISE EXCEPTION 'v12: window % not in state', v_choice;
    END IF;
    RETURN v12_fanout_open_lines(
        v_state ->> 'doc_id', v_state ->> 'query',
        (v_win ->> 'from')::int, (v_win ->> 'to')::int);
END;
$$;

-- Ranked rows: explode the 'where' probabilities back into table rows.
CREATE FUNCTION v12_fanout_top(p_batch uuid, p_k int DEFAULT 5)
RETURNS TABLE (line_no int, line text, probability numeric)
LANGUAGE sql STABLE AS $$
    SELECT substr(kv.key, 2)::int AS line_no,
           d.line,
           (kv.value #>> '{}')::numeric AS probability
      FROM jev_decisions dec
      CROSS JOIN LATERAL jsonb_each(dec.answer -> 'probabilities') AS kv
      JOIN LATERAL (
            SELECT fd.line
              FROM fanout_docs fd
             WHERE fd.doc_id = (SELECT b.state ->> 'doc_id'
                                  FROM jev_batches b
                                 WHERE b.batch_id = dec.batch_id)
               AND fd.line_no = substr(kv.key, 2)::int
      ) d ON true
     WHERE dec.batch_id = p_batch
       AND dec.question_id = 'where'
     ORDER BY probability DESC, line_no
     LIMIT p_k;
$$;

-- Existence verdict from the thresholded Noul (fallback = 'absent').
CREATE FUNCTION v12_fanout_verdict(p_batch uuid) RETURNS text
LANGUAGE plpgsql STABLE AS $$
DECLARE
    v_verdict text;
BEGIN
    SELECT verdict INTO v_verdict FROM v12_routes
     WHERE batch_id = p_batch AND question_id = 'exists';
    IF v_verdict IS NULL THEN
        RAISE EXCEPTION 'v12: no exists decision for %', p_batch;
    END IF;
    RETURN CASE WHEN v_verdict = 'act' THEN 'found' ELSE 'absent' END;
END;
$$;

INSERT INTO thresholds (purpose, question_id, act_min, review_min, fallback)
VALUES ('fanout', 'exists', 0.7, 0.35, 'absent');
