"""W2 gate for the exact DuckDB development wheel used by v6."""
from __future__ import annotations

import platform
import re
import sys
import threading
import time

import duckdb

EXPECTED_PACKAGE = "1.6.0.dev365"
EXPECTED_ENGINE = "v2.0.0-alpha38615"


def check(label: str, condition: bool, detail: object = "") -> None:
    print(f"[{('PASS' if condition else 'FAIL')}] {label}" + (f": {detail}" if detail else ""))
    if not condition:
        raise AssertionError(f"{label}: {detail}")


def raises(fn, pattern: str | None = None) -> str:
    try:
        fn()
    except Exception as exc:
        msg = f"{type(exc).__name__}: {exc}"
        if pattern:
            check(f"raises {pattern}", re.search(pattern, msg, re.I) is not None, msg)
        return msg
    raise AssertionError("expected exception")


def hardened_connection():
    con = duckdb.connect()
    # These settings must be applied before any extension/file operation.
    con.execute("SET autoinstall_known_extensions=false")
    con.execute("SET autoload_known_extensions=false")
    con.execute("SET enable_external_access=false")
    con.execute("SET memory_limit='512 MiB'")
    return con


def main() -> int:
    check("exact Python package", duckdb.__version__ == EXPECTED_PACKAGE, duckdb.__version__)
    check("macOS only", sys.platform == "darwin", sys.platform)
    check("arm64 only", platform.machine() == "arm64", platform.machine())
    check("CPython 3.12 only", sys.version_info[:2] == (3, 12), sys.version)

    con = hardened_connection()
    try:
        engine = con.execute("SELECT version()").fetchone()[0]
        check("expected alpha engine", engine == EXPECTED_ENGINE, engine)
        settings = dict(con.execute(
            "SELECT name, value FROM duckdb_settings() WHERE name IN "
            "('autoinstall_known_extensions','autoload_known_extensions',"
            "'enable_external_access','memory_limit')"
        ).fetchall())
        check("autoinstall disabled", settings["autoinstall_known_extensions"] == "false", settings)
        check("autoload disabled", settings["autoload_known_extensions"] == "false", settings)
        check("external access disabled", settings["enable_external_access"] == "false", settings)
        check("memory limit set", settings["memory_limit"] in {"512 MiB", "512.0 MiB"}, settings)

        raises(lambda: con.execute("SET enable_external_access=true"), "external")
        raises(lambda: con.execute("INSTALL postgres"))
        raises(lambda: con.execute("LOAD postgres"))
        raises(lambda: con.execute("SELECT * FROM read_csv_auto('/tmp/nope.csv')"))

        con.execute("CREATE TABLE source_data(x INTEGER, y INTEGER)")
        con.execute("INSERT INTO source_data VALUES (1, 10), (2, 20), (3, 30)")

        # The MVP materialization path: explicit name generated by the worker.
        con.execute("BEGIN")
        con.execute("CREATE TEMP VIEW v_first AS SELECT x, y * 2 AS y2 FROM source_data WHERE x > 1")
        con.execute("ROLLBACK")
        count = con.execute(
            "SELECT count(*) FROM duckdb_views() WHERE view_name='v_first'"
        ).fetchone()[0]
        check("new TEMP VIEW rolls back", count == 0, count)

        con.execute("BEGIN")
        con.execute("CREATE TEMP VIEW v_first AS SELECT x, y * 2 AS y2 FROM source_data WHERE x > 1")
        con.execute("COMMIT")
        rows = con.execute("SELECT * FROM v_first ORDER BY x").fetchall()
        check("TEMP VIEW commits", rows == [(2, 40), (3, 60)], rows)
        raises(lambda: con.execute("CREATE TEMP VIEW v_first AS SELECT 1"), "already exists|exists")

        # The announced 2.0 trailing alias is not a materialization instruction.
        con.execute("SELECT x FROM source_data AS named_out")
        aliases = con.execute(
            "SELECT count(*) FROM duckdb_views() WHERE view_name='named_out'"
        ).fetchone()[0]
        check("trailing AS is not a named view", aliases == 0, aliases)

        # extract_statements alone is insufficient: hidden DML/COPY may be typed SELECT.
        stmts = con.extract_statements("SELECT 1; SELECT 2")
        check("extract_statements sees two statements", len(stmts) == 2, len(stmts))
        dml_cte = "WITH ins AS (INSERT INTO source_data VALUES (9, 90) RETURNING *) SELECT * FROM ins"
        dml_type = con.extract_statements(dml_cte)[0].type
        check("DML-in-CTE is recognized as a risky SELECT-shaped statement", str(dml_type).upper().endswith("SELECT"), dml_type)
        before = con.execute("SELECT count(*) FROM source_data").fetchone()[0]
        con.execute(dml_cte)
        after = con.execute("SELECT count(*) FROM source_data").fetchone()[0]
        check("DML-in-CTE fact recorded", after == before + 1, (before, after))

        # CTE and FROM-first are valid read queries for the eventual validator.
        check("FROM-first works", con.execute("FROM source_data SELECT x ORDER BY x LIMIT 2").fetchall() == [(1,), (2,)])
        check("recursive CTE works", con.execute(
            "WITH RECURSIVE c(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM c WHERE n<3) SELECT * FROM c"
        ).fetchall() == [(1,), (2,), (3,)])
        check("QUALIFY works", con.execute(
            "SELECT x, row_number() OVER (ORDER BY x) AS rn FROM source_data QUALIFY rn <= 2"
        ).fetchall() == [(1, 1), (2, 2)])

        # interrupt() is the cancellation primitive used by the future worker.
        result: dict[str, object] = {}
        def run_long_query() -> None:
            try:
                con.execute("SELECT sum(i) FROM range(1000000000000) t(i)").fetchall()
                result["completed"] = True
            except Exception as exc:
                result["error"] = f"{type(exc).__name__}: {exc}"
        thread = threading.Thread(target=run_long_query)
        thread.start()
        time.sleep(0.05)
        check("connection exposes interrupt", hasattr(con, "interrupt"))
        con.interrupt()
        thread.join(timeout=5)
        check("interrupt terminates query", not thread.is_alive(), result)
        check("interrupt reports an error", "error" in result, result)

        print("[W2] all gates passed")
        return 0
    finally:
        con.close()


if __name__ == "__main__":
    raise SystemExit(main())
