"""Phase 0 MinerU identity package. Constants only; no evaluator import."""

from v7.mineru.contracts import (
    CANONICAL_CONTENT_LIST,
    EXECUTION_BACKEND,
    HARNESS_REVISION,
    IDENTITY_LOCK_REL,
    IDENTITY_PROFILE_REL,
    MINERU_PARSER_EXPECTED,
    MINERU_VERSION,
    MINERU_WHEEL_SHA256,
    MODEL_MANIFEST_SHA256,
    PAGE_SIZE,
    PDF_SHA256,
    PROFILE_ID,
    P19S_EVIDENCE_SHA256,
)

__all__ = [
    "CANONICAL_CONTENT_LIST",
    "EXECUTION_BACKEND",
    "HARNESS_REVISION",
    "IDENTITY_LOCK_REL",
    "IDENTITY_PROFILE_REL",
    "MINERU_PARSER_EXPECTED",
    "MINERU_VERSION",
    "MINERU_WHEEL_SHA256",
    "MODEL_MANIFEST_SHA256",
    "PAGE_SIZE",
    "PDF_SHA256",
    "PROFILE_ID",
    "P19S_EVIDENCE_SHA256",
]
